### ISSUE TITLE
Syntax error when executing cradle.py

### ISSUE THREAD

**Issue by dr4lekhine** [naksyn/Pyramid#7]
Hello,
 

When trying to execute on Windows Server 2012 R2 "python cradle.py" (Python 3.10.6), I´m getting the following syntax error:

![image](https://user-images.githubusercontent.com/72524642/232249006-5df93674-de98-45e3-947d-f4c9d1daba21.png)

On server side, looks like this (when "ENTER PEM pass phrase", I entered the one I used upon execution of):
**openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365**

**python3 pyramid.py -p 443 -ssl -u testuser -pass Sup3rP4ss! -enc "chacha20" -passenc "TestPass1" -server "10.8.40.14" -generate**

![image](https://user-images.githubusercontent.com/72524642/232250137-cb98240c-cc4d-4b69-8f1c-45e66c2054ff.png)

I also tried running cradle on a Windows11 box with the same results. What I´m doing wrong?. The code looks like this:

![image](https://user-images.githubusercontent.com/72524642/232249308-4274fa43-c67e-420c-abd5-8236a38d74a5.png)

Thanks in advance.

Regards.

**Comment by naksyn** [comment]
Hi, your cradle.py is working fine, there's a typo from my end in mod-bh.py.
I just pushed the correction.
 
import### AUTO-GENERATED PYRAMID CONFIG ### DELIMITER

was substituted with:

import inspect

### AUTO-GENERATED PYRAMID CONFIG ### DELIMITER

Thanks for pointing that out. Let me know now if the issue is solved.

Cheers

**Comment by dr4lekhine** [comment]
Hi!

Yes. It´s solved now!

Thank you.


N.
